spotify_analytics:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('DBT_DEV_DATABASE') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      threads: 1

    ci:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('DBT_CI_DATABASE') }}"
      schema: "{{ env_var('DBT_CI_SCHEMA') }}"
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      threads: 1

    prod:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('DBT_PROD_DATABASE') }}"
      schema: "{{ env_var('DBT_PROD_SCHEMA') }}"
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      threads: 1

  target: dev